name: network

on:
  push:

jobs:
  push-settings:
   permissions:
     actions: write
     checks: write
     contents: write
     deployments: write
     issues: write
     packages: write
     pull-requests: write
     repository-projects: write
     security-events: write
     statuses: write
  job-with-network-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Move directory
        run: cd /home/runner/work/Scan-Report/Scan-Report
      - name: Update apt Package lists
        run: sudo apt update -y
      - name: Upgrade apt version
        run: sudo apt upgrade -y
      - name: Install Nmap
        run: sudo apt install nmap -y
      - name: Confirm Nmap version
        run: nmap --version
      - name: Update apt-get Package lists
        run: sudo apt-get update
      - name: Upgrade apt-get version
        run: sudo apt-get upgrade
      - name: Install Xsltproc
        run: sudo apt-get install xsltproc
      - name: Scan network
        run: sudo bash scan.sh >> $GITHUB_STEP_SUMMARY
      - name: Register user email
        run: git config --global user.email "uho02741358@gmail.com"
      - name: Register user name
        run: git config --global user.name "Uchida16104"
      - name: Initialize Git
        run: git init
      - name: Register files
        run: git add .
      - name: Commit files
        run: git commit -m "Committed"
      - name: Push files
        run: git push origin main
