name: network

on:
  push:

jobs:
  job-with-network-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Package lists
        run: sudo apt update -y
      - name: Upgrade the version
        run: sudo apt upgrade -y
      - name: Install Nmap
        run: sudo apt install nmap -y
      - name: Confirm Nmap version
        run: nmap --version
      - name: Scan network
        run: sudo bash scan.sh >> $GITHUB_STEP_SUMMARY
      - name: Move directory
        run: cd /home/runner/work/Scan-Report/Scan-Report
      - name: Initialize Git
        run: git init
      - name: Make file
        run: vim scan.xml
      - name: Register file
        run: git add scan.xml
      - name: Commit file
        run: git commit -m "Committed"      
