name: network

on:
  push:
  schedule:
    - cron: "*/20 * * * *"
    
jobs:
  job-with-network-scan:
    runs-on: ubuntu-latest
    permissions:
     actions: write
     checks: write
     contents: write
     deployments: write
     issues: write
     packages: write
     pull-requests: write
     repository-projects: write
     security-events: write
     statuses: write
    steps:
      - uses: actions/checkout@v3
      - name: Move directory
        run: cd /home/runner/work/Scan-Report/Scan-Report
      - name: Update apt Package lists
        run: sudo apt update -y
      - name: Upgrade apt version
        run: sudo apt upgrade -y
      - name: Install Nmap
        run: sudo apt install nmap -y
      - name: Confirm Nmap version
        run: nmap --version
      - name: Update apt-get Package lists
        run: sudo apt-get update
      - name: Upgrade apt-get version
        run: sudo apt-get upgrade
      - name: Install Xsltproc
        run: sudo apt-get install xsltproc
      - name: Prepare to install LFS
        run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - name: Pre-install LFS
        run: sudo apt-get install git-lfs
      - name: Install LFS
        run: git lfs install
      - name: Confirm LFS version
        run: git lfs --version
      - name: Enable LFS
        uses: actions/checkout@v3
        with:
          lfs: true
          clean: false
      - name: Reset commits
        run: git reset --hard
      - name: Scan network
        run: sudo bash scan.sh >> $GITHUB_STEP_SUMMARY
      - name: Convert xml to html
        run: xsltproc index.xml -o index.html
      - name: Register user email
        run: git config --global user.email "${{ secrets.EMAIL }}"
      - name: Register user name
        run: git config --global user.name "${{ secrets.NAME }}"
      - name: Initialize Git
        run: git init
      - name: Register files
        run: git add .
      - name: Commit files
        run: git commit -m "Upload Zend framework 3 skeleton" -m "Use GitHub web GUI"
      - name: Push files
        run: git push origin main
